a = input('Digite Algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só espaço ? ', a.isspace())
print('É um numero ? ', a.isnumeric())
print('É alfabetico ? ', a.isalpha())
print('É alfanumero ? ', a.isalnum())
print('Está em minuscula ?',a.islower())
print('Esta maiuscula ? ', a.isupper())
print('Está capitalizada ? ', a.istitle())
